#release configuration
#Wed Mar 25 17:22:26 CET 2026
completedPhase=end-release
exec.activateProfiles=deploy-to-scijava
exec.additionalArguments=-Dgpg.skip\=true 
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.fiji.plugin\:DeXtrusion_Appose=0.1.4-SNAPSHOT
project.rel.fiji.plugin\:DeXtrusion_Appose=0.1.3
project.scm.fiji.plugin\:DeXtrusion_Appose.connection=scm\:git\:git\://github.com/Image-Analysis-Hub/dextrusion-appose
project.scm.fiji.plugin\:DeXtrusion_Appose.developerConnection=scm\:git\:git@github.com\:Image-Analysis-Hub/dextrusion-appose
project.scm.fiji.plugin\:DeXtrusion_Appose.tag=DeXtrusion_Appose-0.1.2
project.scm.fiji.plugin\:DeXtrusion_Appose.url=https\://github.com/Image-Analysis-Hub/dextrusion-appose
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=false
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=DeXtrusion_Appose-0.1.3
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:https\://github.com/Image-Analysis-Hub/dextrusion-appose
